name: PandaGPT
version: 1.0
main: cn.panda.pandagpt.ChatGPTIntegration
api-version: 1.12
description: An intelligent assistant plugin that integrates ChatGPT into Minecraft.

commands:
  panda:
    description: Chat with the Panda AI assistant.
    usage: /panda <your question>
  pandaadmin:
    description: Manage the Panda plugin.
    usage: /pandaadmin <reload|clearchat>

permissions:
  pandagpt.admin:
    description: Allows the use of Panda management commands.
    default: op
